# syntax = docker/dockerfile-upstream:1.15.1-labs

FROM golang:1.24 AS build
WORKDIR /src
COPY <<EOF ./main.go
package main

import "fmt"

func main() {
  fmt.Println("hello, world")
}
EOF
RUN go build -o /bin/hello ./main.go

FROM scratch AS hello
COPY --from=build /bin/hello /bin/hello
CMD ["/bin/hello"]
